@startuml
class Bird {
    - bird1 : Texture2D
    - bird2 : Texture2D
    - maxHeight : float
    - minHeight : float
    - speed : float
    - random : Random
    - currentFrame : int
    - frameTime : float
    - totalFrame : int
    - elapsedTime : float
    - zoom : float
    - displayed : List<Vector2>
    - isGenerated : bool
    - spawnAfter : float
    - duration : float
    - totalDuration : float
    + Bird(bird1:Texture2D, bird2:Texture2D, maxHeight:float, minHeight:float, speed:float)
    + Update(gameTime:GameTime, _graphics:GraphicsDeviceManager) : List<Vector2>
    + Draw(spriteBatch:SpriteBatch) : void
    - GetNextSpawnAfter() : float
    - GetNextHeight() : float
}
@enduml
