@startuml
class Cactus {
    - cactuses : List<Texture2D>
    - size : int
    - originalPosHeihgt : float
    - speed : float
    - displayed : List<Entity>
    - random : Random
    + Cactus(cactuses:List<Texture2D>, originalPosHeihgt:float, speed:float)
    + Update(gameTime:GameTime, _graphics:GraphicsDeviceManager, groundSpeed:float) : List<Entity>
    - GetNextSpawnAfter() : float
    + GetNextCactuses(_graphics:GraphicsDeviceManager) : void
    - getZoom() : float
    + Draw(spriteBatch:SpriteBatch) : void
    - getZoomedColor(original:Color[], originWidth:int, originHeight:int, newWidth:int, newHeight:int) : Color[]
}
class Entity {
    + pos : Vector2
    + cactus : Texture2D
    + color : Color[]
    + zoom : float
    + Entity(pos:Vector2, cactus:Texture2D, color:Color[], zoom:float)
}
Cactus +-- Entity
@enduml
